### ISSUE TITLE
Fourth Page

### ISSUE THREAD

**Issue by qlemql** [qlemql/toyproject_team8#16]
1. Modal
- [ Show result ]
- [ Result name ]
- [ Description ] 
- [ Recommended product ]
- [ Slide ]

**Comment by minjujung** [comment]
완료했어요!

**Comment by minjujung** [comment]
맨 마지막 페이지여서 이후에 css 쪽 z-index내용 수정해야 modal창이 제대로 작동할 것 같아요!
